# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4a3cb9ac9a92da6eac368b389e177e29fe4601952b3fbacc32660992c657bf4e4555ded9b24767b73dbd5843857a874198a47d1adf2f60dd0808a4ef1ac14d3a

test:
  secret_key_base: abb15aaa5a0198871ffde6a948a605d4940a94bce592d4dd07733c6a7cbde0d32742eb7f332877c7efceb5627aa5b4dae979df519150442a174dfb7c87af61de

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
